import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";

export async function getStaticProps() {
  // get the post
  const files = fs.readdirSync("posts");
  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");
    const readFiles = fs.readFileSync(`posts/${filename}`);
    const { data: frontMatter } = matter(readFiles);

    return {
      slug,
      frontMatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  console.log(`posts: ${posts}`);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='p-10'>
          {posts?.map((post) => {
            return (
              <Link key={`${post.slug}`} href={`/blog/${post.slug}`}>
                <a>
                  <div className='mb-4'>
                    <h1 className='text-xl py-3'>{post.frontMatter.title}</h1>
                    <p>{post.frontMatter.metaDesc}</p>
                  </div>
                </a>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}
